# Generated by Django 4.2.11 on 2024-03-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstrumentGroupMaster",
            fields=[
                ("tool_id", models.AutoField(primary_key=True, serialize=False)),
                ("tool_group_name", models.CharField(max_length=24)),
                ("tool_group_code", models.CharField(max_length=8)),
                ("instrument_type", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentModel",
            fields=[
                ("instrument_no", models.AutoField(primary_key=True, serialize=False)),
                ("instrument_name", models.CharField(max_length=16)),
                ("manufacturer_name", models.CharField(max_length=24)),
                ("year_of_purchase", models.DateField()),
                ("gst", models.SmallIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("instrument_range", models.CharField(max_length=12)),
                ("least_count", models.CharField(max_length=8)),
                ("calibration_frequency", models.IntegerField()),
                (
                    "type_of_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.instrumentgroupmaster",
                    ),
                ),
            ],
        ),
    ]
