# Generated by Django 4.2.11 on 2024-03-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="instrument_type",
            field=models.CharField(max_length=16),
        ),
    ]
