# Generated by Django 4.2.13 on 2024-06-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentmodel",
            name="current_shed",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="type_of_tool",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.instrumentgroupmaster",
            ),
        ),
    ]
