# Generated by Django 4.2.13 on 2024-06-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_instrumentmodel_current_shed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="tool_family",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.instrumentfamilygroup",
            ),
        ),
    ]
