# Generated by Django 4.2.13 on 2024-06-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_sheddetails_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShedUser",
            fields=[
                ("sheduser_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.sheddetails",
                    ),
                ),
            ],
        ),
    ]
