# Generated by Django 4.2.11 on 2024-03-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_instrumentmodel_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShedDetails",
            fields=[
                ("shed_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=24)),
                ("location", models.CharField(max_length=16)),
                ("phone_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="instrument_range",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="ShedTools",
            fields=[
                ("shedtool_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.sheddetails",
                    ),
                ),
                (
                    "using_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.instrumentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentReport",
            fields=[
                (
                    "instrument_report_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
                ("lead_time", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.instrumentmodel",
                    ),
                ),
            ],
        ),
    ]
