# Generated by Django 4.2.13 on 2024-06-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_sheduser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instrumentmodel",
            unique_together={("instrument_name", "type_of_tool")},
        ),
        migrations.AlterField(
            model_name="shedtools",
            name="using_tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app1.instrumentmodel"
            ),
        ),
    ]
