# Generated by Django 4.2.13 on 2024-06-23 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_instrumentmodel_notification_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentmodel",
            name="notification_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
