# Generated by Django 4.2.11 on 2024-03-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_toolmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolmovement",
            name="destination_shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tool_movement_destination",
                to="app1.sheddetails",
            ),
        ),
        migrations.CreateModel(
            name="AcceptancePendingList",
            fields=[
                ("slip_no", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("entered_by", models.CharField(max_length=24)),
                (
                    "destination_shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance_pending_destination",
                        to="app1.sheddetails",
                    ),
                ),
                (
                    "instrument_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.instrumentmodel",
                    ),
                ),
            ],
        ),
    ]
