# Generated by Django 4.2.13 on 2024-06-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_instrumentmodel_notification_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instrumentfamilygroup", unique_together={("instrument_family_name",)},
        ),
        migrations.AlterUniqueTogether(
            name="instrumentgroupmaster", unique_together={("tool_group_name",)},
        ),
        migrations.AlterUniqueTogether(
            name="instrumentmodel", unique_together={("instrument_name",)},
        ),
        migrations.AlterUniqueTogether(
            name="sheddetails", unique_together={("name",)},
        ),
    ]
