# Generated by Django 4.2.13 on 2024-06-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_shedtools_shed_alter_shedtools_using_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentmodel",
            name="current_shed",
            field=models.ForeignKey(
                blank=True,
                default=6,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="shedtools",
            name="shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.sheddetails"
            ),
        ),
    ]
