# Generated by Django 4.2.11 on 2024-03-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_instrumentreport_instrument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceTools",
            fields=[
                ("servicetool_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.serviceorder",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.instrumentmodel",
                    ),
                ),
            ],
        ),
    ]
