# Generated by Django 4.2.11 on 2024-03-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_serviceorder_servicetools"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="servicetools", unique_together={("service", "tool")},
        ),
    ]
