# Generated by Django 4.2.11 on 2024-03-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_alter_servicetools_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportOrder",
            fields=[
                ("movement_id", models.AutoField(primary_key=True, serialize=False)),
                ("movement_date", models.DateField()),
                ("acknowledgment", models.BooleanField(default=False)),
                ("tool_count", models.IntegerField()),
                (
                    "destination_shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="destination_shed_transport_order",
                        to="app1.sheddetails",
                    ),
                ),
                (
                    "source_shed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="source_shed_transport_order",
                        to="app1.sheddetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="tool_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="toolmovement",
            name="source_shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tool_movement_source_shed",
                to="app1.sheddetails",
            ),
        ),
        migrations.CreateModel(
            name="TransportTools",
            fields=[
                (
                    "transporttool_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.instrumentmodel",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.transportorder",
                    ),
                ),
            ],
            options={"unique_together": {("transport", "tool")},},
        ),
    ]
