# Generated by Django 4.2.11 on 2024-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_transportorder_serviceorder_tool_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=24)),
                ("location", models.CharField(max_length=16)),
                ("address", models.CharField(max_length=64)),
                ("phone_number", models.CharField(max_length=10)),
            ],
        ),
    ]
