# Generated by Django 4.2.11 on 2024-03-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSent",
            fields=[
                ("vendorsent_id", models.AutoField(primary_key=True, serialize=False)),
                ("sent_date", models.DateField()),
                ("tool_count", models.IntegerField()),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.transporttools",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app1.vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorReceived",
            fields=[
                (
                    "vendorreceived_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("received_date", models.DateField()),
                ("tool_count", models.IntegerField()),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.transporttools",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app1.vendor"
                    ),
                ),
            ],
        ),
    ]
