# Generated by Django 4.2.11 on 2024-03-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_vendorsent_vendorreceived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorreceived",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app1.transportorder"
            ),
        ),
        migrations.AlterField(
            model_name="vendorsent",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app1.transportorder"
            ),
        ),
    ]
