# Generated by Django 4.2.11 on 2024-03-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_alter_vendorreceived_tool_alter_vendorsent_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorHandles",
            fields=[
                (
                    "vendorhandle_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("turnaround_time", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app1.instrumentmodel",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app1.vendor"
                    ),
                ),
            ],
        ),
    ]
