# Generated by Django 4.2.11 on 2024-03-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_vendorhandles"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentFamilyGroup",
            fields=[
                (
                    "instrumentfamilyid",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("instrument_family_name", models.CharField(max_length=24)),
                (
                    "instrument_group_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.instrumentgroupmaster",
                    ),
                ),
            ],
        ),
    ]
