# Generated by Django 4.2.11 on 2024-03-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_instrumentfamilygroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="vendor",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app1.vendor"
            ),
            preserve_default=False,
        ),
    ]
