# Generated by Django 4.2.11 on 2024-03-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_servicetools_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vendorsent", name="tool",),
        migrations.RemoveField(model_name="vendorsent", name="vendor",),
        migrations.DeleteModel(name="VendorReceived",),
        migrations.DeleteModel(name="VendorSent",),
    ]
