# Generated by Django 4.2.11 on 2024-03-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_deliverychallan_deliverychallantools"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationReport",
            fields=[
                (
                    "calibrationtool_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("calibration_date", models.DateField()),
                ("calibration_report_no", models.CharField(max_length=32)),
                ("calibration_agency", models.CharField(max_length=32)),
                ("result", models.FloatField()),
                ("action", models.CharField(max_length=16)),
                ("next_calibration_date", models.DateField()),
                ("remark", models.TextField()),
                (
                    "calibration_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.instrumentmodel",
                    ),
                ),
            ],
        ),
    ]
