# Generated by Django 4.2.11 on 2024-03-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_instrumenttransporthistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="toolmovement", name="destination_shed",),
        migrations.RemoveField(model_name="toolmovement", name="instrument_name",),
        migrations.RemoveField(model_name="toolmovement", name="source_shed",),
        migrations.RemoveField(model_name="toolmovement", name="tool",),
        migrations.DeleteModel(name="InstrumentTransportHistory",),
        migrations.DeleteModel(name="ToolMovement",),
    ]
