# Generated by Django 4.2.11 on 2024-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_deliverychallantools_calibration_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationreport",
            name="notification_date",
            field=models.DateField(default="2024-02-19"),
            preserve_default=False,
        ),
    ]
