# Generated by Django 4.2.11 on 2024-04-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0024_calibrationreport_notification_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shedtools",
            name="shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.sheddetails"
            ),
        ),
        migrations.AlterField(
            model_name="shedtools",
            name="using_tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.instrumentmodel"
            ),
        ),
    ]
