# Generated by Django 4.2.11 on 2024-04-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_alter_shedtools_shed_alter_shedtools_using_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverychallan",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.serviceorder"
            ),
        ),
        migrations.AlterField(
            model_name="deliverychallan",
            name="shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shed_delivery_challan",
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="deliverychallan",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.vendor"
            ),
        ),
        migrations.AlterField(
            model_name="deliverychallantools",
            name="deliverychallan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.deliverychallan"
            ),
        ),
        migrations.AlterField(
            model_name="deliverychallantools",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.instrumentmodel"
            ),
        ),
        migrations.AlterField(
            model_name="servicetools",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.serviceorder"
            ),
        ),
        migrations.AlterField(
            model_name="servicetools",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.instrumentmodel"
            ),
        ),
        migrations.AlterField(
            model_name="servicetools",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.vendor"
            ),
        ),
        migrations.AlterField(
            model_name="transportorder",
            name="destination_shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_shed_transport_order",
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="transportorder",
            name="source_shed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_shed_transport_order",
                to="app1.sheddetails",
            ),
        ),
        migrations.AlterField(
            model_name="vendorhandles",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.instrumentmodel"
            ),
        ),
        migrations.AlterField(
            model_name="vendorhandles",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.vendor"
            ),
        ),
    ]
