# Generated by Django 4.2.11 on 2024-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_alter_deliverychallan_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentmodel",
            name="service_status",
            field=models.BooleanField(default=False),
        ),
    ]
