# Generated by Django 4.2.11 on 2024-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0027_instrumentmodel_service_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "file",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="news_files/"
                    ),
                ),
            ],
        ),
    ]
