# Generated by Django 4.2.11 on 2024-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0032_vendor_email_vendor_nabl_certificate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorType",
            fields=[
                ("vendortype_id", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_type", models.CharField(max_length=32)),
            ],
        ),
    ]
