# Generated by Django 4.2.11 on 2024-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0034_vendor_vendor_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                ("servicetype_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_type", models.CharField(max_length=32)),
            ],
        ),
    ]
