# Generated by Django 4.2.11 on 2024-05-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0035_servicetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetools",
            name="service_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="app1.servicetype",
            ),
        ),
    ]
