# Generated by Django 4.2.11 on 2024-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0036_servicetools_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetools",
            name="service_remarks",
            field=models.TextField(blank=True, default="good", null=True),
        ),
    ]
