# Generated by Django 4.2.11 on 2024-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0037_servicetools_service_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporttools",
            name="tool_movement_remarks",
            field=models.TextField(blank=True, default="good", null=True),
        ),
    ]
