# Generated by Django 4.2.13 on 2024-06-01 14:06

import app1.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0038_transporttools_tool_movement_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationreport",
            name="calibration_report_file2",
            field=models.FileField(
                default=app1.models.default_report_file,
                max_length=250,
                null=True,
                upload_to="calibration_reports2/",
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transportorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-06-01 15:30:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="instrumentfamilygroup",
            name="instrument_family_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="instrument_type",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="tool_group_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="instrument_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="manufacturer_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="sheddetails",
            name="location",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="sheddetails",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="vendor", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="vendor", name="location", field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="nabl_number",
            field=models.CharField(blank=True, default="0", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="vendor", name="name", field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="app1.vendortype",
            ),
        ),
    ]
