# Generated by Django 4.2.13 on 2024-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0039_calibrationreport_calibration_report_file2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporttools",
            name="acknowledgment",
            field=models.BooleanField(default=False),
        ),
    ]
