# Generated by Django 4.2.13 on 2024-06-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0042_alter_serviceorder_amount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shedtools", unique_together={("shed", "using_tool")},
        ),
        migrations.AlterUniqueTogether(
            name="vendorhandles", unique_together={("vendor", "tool")},
        ),
    ]
