# Generated by Django 4.2.13 on 2024-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0043_alter_shedtools_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
