# Generated by Django 4.2.13 on 2024-06-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0044_alter_serviceorder_amount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shedtools", unique_together={("using_tool",)},
        ),
    ]
