# Generated by Django 4.2.13 on 2024-06-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0045_alter_shedtools_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationreport",
            name="remark",
            field=models.TextField(blank=True, default="Calibration", null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="description",
            field=models.TextField(blank=True, default="Service", null=True),
        ),
    ]
