# Generated by Django 4.2.13 on 2024-06-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0048_serviceorder_service_pending"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instrumentmodel", unique_together={("instrument_name",)},
        ),
    ]
