# Generated by Django 4.2.13 on 2024-06-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0051_alter_instrumentfamilygroup_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentgroupmaster", name="instrument_type",
        ),
    ]
