# Generated by Django 4.2.13 on 2024-06-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0052_remove_instrumentgroupmaster_instrument_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentmodel",
            name="current_shed",
            field=models.ForeignKey(
                blank=True,
                default=6,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.sheddetails",
            ),
        ),
    ]
