# Generated by Django 4.2.13 on 2024-06-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0053_instrumentmodel_current_shed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentmodel",
            name="calibration_frequency",
            field=models.IntegerField(blank=True, default=365, null=True),
        ),
    ]
