# Generated by Django 4.2.13 on 2024-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0054_alter_instrumentmodel_calibration_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationreport",
            name="action",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationreport",
            name="calibration_agency",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationreport",
            name="result",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="gst",
            field=models.SmallIntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="year_of_purchase",
            field=models.DateField(blank=True, null=True),
        ),
    ]
