# Generated by Django 4.2.13 on 2024-06-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0055_alter_calibrationreport_action_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instrumentgroupmaster", unique_together=set(),
        ),
    ]
