# Generated by Django 4.2.13 on 2024-06-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0057_alter_instrumentfamilygroup_instrument_group_master_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instrumentfamilygroup",
            old_name="instrumentfamilyid",
            new_name="instrument_family_id",
        ),
        migrations.RenameField(
            model_name="instrumentgroupmaster",
            old_name="tool_id",
            new_name="tool_group_id",
        ),
    ]
