# Generated by Django 4.2.13 on 2024-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app1",
            "0058_rename_instrumentfamilyid_instrumentfamilygroup_instrument_family_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="tool_group_name",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
