# Generated by Django 4.2.13 on 2024-06-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0059_alter_instrumentgroupmaster_tool_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentfamilygroup",
            name="instrument_group_master",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="app1.instrumentgroupmaster",
            ),
        ),
    ]
