# Generated by Django 4.2.13 on 2024-06-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0060_alter_instrumentfamilygroup_instrument_group_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationreport",
            name="action",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationreport",
            name="calibration_agency",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationreport",
            name="result",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentfamilygroup",
            name="instrument_group_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="app1.instrumentgroupmaster",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentgroupmaster",
            name="tool_group_name",
            field=models.CharField(default="Tool", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="description",
            field=models.CharField(blank=True, default=None, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="instrument_range",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="least_count",
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentmodel",
            name="manufacturer_name",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="servicetools",
            name="service_remarks",
            field=models.TextField(blank=True, default="Service Tool", null=True),
        ),
        migrations.AlterField(
            model_name="transporttools",
            name="tool_movement_remarks",
            field=models.TextField(blank=True, default="Transport Tool", null=True),
        ),
    ]
