# Generated by Django 4.2.13 on 2024-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0061_alter_calibrationreport_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="service_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="servicetools",
            name="service_pending_tool",
            field=models.BooleanField(default=True),
        ),
    ]
